# Generated by Django 5.2.15 on 2026-06-12 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0005_incident_registered_user_incidentassignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="registered_user",
            field=models.ForeignKey(
                blank=True,
                help_text="The system profile linked to the device hash that triggered this report",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="incidents",
                to="incidents.registereduser",
            ),
        ),
    ]
